#!/usr/bin/env bash
# Relocate a Claude Code session so it resumes from a different cwd.
#
# `claude --resume <id>` is cwd-scoped: it only finds sessions stored under the
# project dir matching the current directory. Moving the transcript into another
# project dir makes it resumable there. New turns record the new cwd, so the
# session genuinely continues in the new location.
#
# Moves the <id>.jsonl AND its companion <id>/ subagent dir, and appends a
# reversal line to an undo script.
#
# Usage:
#   move-session.sh <session-id> <target-cwd> [--dry-run]
#   move-session.sh f514ad92-... /Users/sma/projects
#
# Deliberately bash, not zsh: zsh does not word-split unquoted parameters, which
# silently turns an id list into one concatenated argument.

set -euo pipefail

ROOT="${CLAUDE_PROJECTS_ROOT:-$HOME/.claude/projects}"
UNDO="${SESSION_MOVE_UNDO:-$HOME/.claude/session-move-undo-$(date +%Y%m%d).sh}"
BUSY_SECONDS=120

die() { echo "error: $*" >&2; exit 1; }

[ $# -ge 2 ] || die "usage: move-session.sh <session-id> <target-cwd> [--dry-run]"
SID="$1"; TARGET_CWD="$2"; DRY="${3:-}"

[ -d "$ROOT" ] || die "projects root not found: $ROOT"
[ -d "$TARGET_CWD" ] || die "target cwd does not exist: $TARGET_CWD"

# cwd -> project dir name: '/' becomes '-'
slugify() { printf '%s' "${1//\//-}"; }
DST_DIR="$ROOT/$(slugify "$TARGET_CWD")"

# Locate the transcript. Only top-level files are resumable sessions, so restrict
# the search to depth 2 and ignore nested subagent transcripts.
SRC_FILE="$(find "$ROOT" -mindepth 2 -maxdepth 2 -name "$SID.jsonl" -print -quit 2>/dev/null || true)"
[ -n "$SRC_FILE" ] || die "no resumable session with id $SID (nested subagent transcripts are not resumable)"
SRC_DIR="$(dirname "$SRC_FILE")"

[ "$SRC_DIR" != "$DST_DIR" ] || die "session already resumes from $TARGET_CWD"

# Refuse to move a transcript that is being written right now: a live session
# holds it open and would keep appending to the old path.
NOW=$(date +%s)
MTIME=$(stat -f %m "$SRC_FILE" 2>/dev/null || stat -c %Y "$SRC_FILE")
AGE=$(( NOW - MTIME ))
if [ "$AGE" -lt "$BUSY_SECONDS" ]; then
    die "session was written ${AGE}s ago and looks live; stop it first (or wait ${BUSY_SECONDS}s)"
fi

[ -e "$DST_DIR/$SID.jsonl" ] && die "collision: $DST_DIR/$SID.jsonl already exists"
[ -e "$DST_DIR/$SID" ] && die "collision: $DST_DIR/$SID already exists"

SUB_COUNT=0
[ -d "$SRC_DIR/$SID" ] && SUB_COUNT=$(find "$SRC_DIR/$SID" -name '*.jsonl' | wc -l | tr -d ' ')

echo "session : $SID"
echo "from    : $SRC_DIR"
echo "to      : $DST_DIR"
echo "subagent: $SUB_COUNT transcripts"

if [ "$DRY" = "--dry-run" ]; then
    echo "(dry run — nothing moved)"
    exit 0
fi

mkdir -p "$DST_DIR"
mv "$SRC_FILE" "$DST_DIR/$SID.jsonl"
[ -d "$SRC_DIR/$SID" ] && mv "$SRC_DIR/$SID" "$DST_DIR/$SID"

if [ ! -f "$UNDO" ]; then
    printf '#!/usr/bin/env bash\n# Reverses session relocations. Generated by move-session.sh.\nset -euo pipefail\n' > "$UNDO"
    chmod +x "$UNDO"
fi
printf 'mv "%s/%s.jsonl" "%s/%s.jsonl"\n[ -d "%s/%s" ] && mv "%s/%s" "%s/%s"\n' \
    "$DST_DIR" "$SID" "$SRC_DIR" "$SID" \
    "$DST_DIR" "$SID" "$DST_DIR" "$SID" "$SRC_DIR" "$SID" >> "$UNDO"

echo "moved. resume with:  cd $TARGET_CWD && claude --resume $SID"
echo "undo script: $UNDO"
